# Generated by Django 4.2.30 on 2026-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('Math', 'Mathematics'), ('Physics', 'Physics'), ('Chem', 'Chemistry')], max_length=25),
        ),
    ]
